### ISSUE TITLE
Some of the SymphonyOSS.RestApiClient sub-project files don't have license headers

### ISSUE THREAD

**Issue by maoo** [symphonyoss/RestApiClient#1]

**Comment by maoo** [comment]
Please ignore the generated files, as specified in NOTICE.txt

**Comment by maoo** [comment]
Since most of the files without proper headers are generated ones, it is ok not to have headers, as long as NOTICE.txt mentions the file patterns (ie this/sub/folder/**.cs)

On a separate track, would be possible to delegate this file generation to the build process, so that it is not necessary to commit generated files in the codebase?

**Comment by jforsell** [comment]
A script will prepend a license header to the generated *.cs files. A few of the other files that were missing a license header will have it added. That leaves us with the following list of exceptions, to be mentioned in the NOTICE file:

**/AssemblyInfo.cs
**/packages.config
src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/**/*.yaml
.travis.yml

**Comment by jforsell** [comment]
The output below is from running the validation script on master in its current state. All files in the output are mentioned in the NOTICE file.

CRIT-3 - List of files not licensed to The Symphony Software Foundation (SSF) ...
===========================
RestApiClient/test/SymphonyOSS.RestApiClient.Tests/Properties/AssemblyInfo.cs RestApiClient/test/SymphonyOSS.RestApiClient.Tests/packages.config RestApiClient/src/SymphonyOSS.RestApiClient/Properties/AssemblyInfo.cs RestApiClient/src/SymphonyOSS.RestApiClient/packages.config RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/AuthenticatorApi/1.0/authenticatorAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/AgentApi/1.38.0/agentAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/PodApi/1.38.0/podAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/Properties/AssemblyInfo.cs RestApiClient/src/SymphonyOSS.RestApiClient.Generated/packages.config RestApiClient/.travis.yml
===========================

CRIT-3 - List of files missing Apache license header
===========================
RestApiClient/test/SymphonyOSS.RestApiClient.Tests/Properties/AssemblyInfo.cs RestApiClient/test/SymphonyOSS.RestApiClient.Tests/packages.config RestApiClient/src/SymphonyOSS.RestApiClient/Properties/AssemblyInfo.cs RestApiClient/src/SymphonyOSS.RestApiClient/packages.config RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/AuthenticatorApi/1.0/authenticatorAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/AgentApi/1.38.0/agentAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/OpenApi/Yaml/PodApi/1.38.0/podAPI.yaml RestApiClient/src/SymphonyOSS.RestApiClient.Generated/Properties/AssemblyInfo.cs RestApiClient/src/SymphonyOSS.RestApiClient.Generated/packages.config RestApiClient/.travis.yml
===========================

Issues have been found and documented above; to fix them, please visit https://symphonyoss.atlassian.net/wiki/x/SAAx
