### ISSUE TITLE
Check third-party licenses

### ISSUE THREAD

**Issue by maoo** [symphonyoss/RestApiClient#17]
Following blogpost http://haacked.com/archive/2015/03/28/download-nuget-package-licenses/ , we need to design a way to automatically check third-party libraries against the list of compatible Apache 2.0 licenses (check [Legal Criteria page](https://symphonyoss.atlassian.net/wiki/display/FM/Legal+Acceptance+Criteria))

Alternatively (or in parallel), test with myget.org the creation of a Nuget feed (aka repository) that proxies and whitelists third-party dependencies that are allowed to be used by SSF .NET code.

**Comment by maoo** [comment]
Added integration with Versioneye - https://www.versioneye.com/user/projects/57b73c371dcdc900430c0b37?child=summary

@jforsell , can you please sign up to Versioneye and send me your username, so I can add you to the project?

**Comment by jforsell** [comment]
Thanks @maoo , I've signed up and my username on Versioneye is jforsell - https://www.versioneye.com/users/jforsell

**Comment by maoo** [comment]
Done, you're part of the `RestApiClient` group in Versioneye. 

You should be able to access the `Settings` tab on https://www.versioneye.com/user/projects/57b73c371dcdc900430c0b37?child=summary . If not, please reopen this issue. TY!
