### ISSUE TITLE
myget.org experiment

### ISSUE THREAD

**Issue by maoo** [symphonyoss/RestApiClient#18]
Try myget.org to build, run tests and publish nightly builds and releases for the RestApiClient project.

If successful, Travis could be deprecated in favour of myget.org

**Comment by maoo** [comment]
I'd still wait for the outcome of #19 to see if this experiment is needed at all

**Comment by jforsell** [comment]
@maoo I just released v0.3.5 from myget.org.

**Comment by maoo** [comment]
Great news, I saw it being published on https://www.nuget.org/profiles/symphonyoss

Was the process fully automated from end to end, including sharing it with the `symphonyoss` NuGet profile? Or was that a one-off configuration?

Also, do you confirm that myget is a complete alternative to Travis, at least for .NET projects?

I'd like to document this approach on https://symphonyoss.atlassian.net/wiki/display/FM/Software+Development+Onboarding for future references, if you think that's a good idea.

**Comment by maoo** [comment]
All done, please check https://www.myget.org/feed/ssf-feed/package/nuget/SymphonyOSS.RestApiClient and http://nuget.org/profiles/symphonyoss
