### ISSUE TITLE
Improve NuGet configuration for SSF artifacts

### ISSUE THREAD

**Issue by maoo** [symphonyoss/RestApiClient#19]
Checking the only existing symphonyOSS released artifact on nuget, the following challenges are noticed:
- There is no landing page for all SSF artifacts
- There is no 2-step publication process (to validate what's being published by SSF officers)
- Need to identify a "scope" (or "groupId", or "namespace") that  identifies an SSF artifact

**Comment by maoo** [comment]
From https://docs.nuget.org/create/managing-package-owners:

"Packages can also utilize a convention for "organizations" to indicate company/group ownership of a package. For example, the Microsoft ASP.NET packages are co-owned by microsoft, aspnet, and sometimes individuals on the feature team. The 'microsoft' and 'aspnet' accounts are simply set up with a mailing list email address that reaches the teams that manage the accounts."

This suggests that we need to:
1. @maoo creates a symphonyoss account on nuget.org
2. @jforsell shares/transfers ownership of the artifact to symphonyoss nuget account
3. @maoo validates the artifacts and publishes it

**Comment by maoo** [comment]
1 is done - https://www.nuget.org/profiles/symphonyoss . Assigning issue to @jforsell

**Comment by maoo** [comment]
Hi @jforsell , have you tried adding https://www.nuget.org/profiles/symphonyoss to the NuGet project? the SSF profile still doesn't show the project.

Thanks!

**Comment by jforsell** [comment]
Hi @maoo - I just added symphonyoss as an owner of the package in NuGet - looks like you'll need to approve the change.

**Comment by maoo** [comment]
Done, thank you SO much!

Now we can claim that we closed the circle for .NET release; although not automated (as with Java, the only automation for now is with NPM and semantic-release), we have walked through all steps to publish OSS code in .NET under the Foundation umbrella.

Thanks a lot for your help @jforsell !
