### ISSUE TITLE
Invoke nuget pack command on master branch builds

### ISSUE THREAD

**Issue by maoo** [symphonyoss/RestApiClient#2]
Now that Travis builds the project correctly, it would be useful to invoke `nuget pack` when the process is done; this needs to happen _only if_ the build is executed on master branch.

/CC @jforsell

**Comment by jforsell** [comment]
The nuget pack command will probably look something like this:

nuget pack src/SymphonyOSS.RestApiClient/SymphonyOSS.RestApiClient.csproj -IncludeReferencedProjects -Prop Configuration=Release

**Comment by maoo** [comment]
A manual build and deployment on NuGet was done last week on https://www.nuget.org/packages/SymphonyOSS.RestApiClient/0.1.0 (thanks @jforsell)

**Comment by maoo** [comment]
Created https://github.com/symphonyoss/contrib-toolbox/blob/master/scripts/release-to-nuget.sh and integrated with Travis, here's the PR - https://github.com/symphonyoss/RestApiClient/pull/20

It needs some testing, since Travis haven't run the build yet. Assigning to @jforsell for review

**Comment by maoo** [comment]
Switching to MyGet solved the issue, see https://www.myget.org/feed/ssf-feed/package/nuget/SymphonyOSS.RestApiClient
