### ISSUE TITLE
DatafeedApi polls once and stops

### ISSUE THREAD

**Issue by stoyandamov** [symphonyoss/RestApiClient#22]
In the assembly `SymphonyOSS.RestApiClient`, in `Api\AgentApi\DatafeedApi.css`, method `ReadDatafeed` polls data in a loop and it traps any API exceptions like this:

``` cs
    while (true)
    {
        try
        {
            var messageList = ReadDatafeed(id, maxMessages);
            // ...
            return messageList;
        }
        catch (ApiException e)
        {
            if (countDatafeedErrors >= retriesAllowed)
            {
                throw;
            }
            ++countDatafeedErrors;
            // ...
            id = CreateDatafeed();
        }
    }
}
```

The problem is that if there's nothing on the feed, the client gets a timeout and an exception is indeed thrown (`e.ErrorCode` is `0`). This error code should be expected (it's not a valid HTTP server status code and _usually_ means timeout) and not re-thrown otherwise `DatafeedApi.Listen` loops if there's data at the moment, and then exits, with no chance to receive further chat messages.

My workaround is to check for `ErrorCode == 0` in the `catch` clause:

``` cs
catch (ApiException e)
{
    if (e.ErrorCode != 0) // HTTP call timeouts should be expected, RIGHT?!
    {
        if (countDatafeedErrors >= retriesAllowed)
        {
            throw;
        }
        ++countDatafeedErrors;
        TraceSource.TraceEvent(
            TraceEventType.Error, 0,
            "Unhandled API exception caught when reading data feed, retrying: {0}", e);
    }
    id = CreateDatafeed();
}
```

I'm not sure if there's a cleaner way to do this but needed it for the codeathon :)

**Comment by jforsell** [comment]
That's interesting, thanks for filing. We haven't seen that behaviour over here. If there are no messages on the datafeed, after just over 30 seconds it returns with an HTTP status 204 (no content) and no exception is thrown, which is consistent with the documentation in agentAPI.yaml.

Is there a proxy between the client and the agent in your environment?

**Comment by stoyandamov** [comment]
No, there's no proxy.

**Comment by stoyandamov** [comment]
I very much doubt that it matters but what might be different on my side is that I've decreased all timeouts to 10 seconds ('cause I can't stand the timeouts during debugging :).

**Comment by jforsell** [comment]
Ah, try and set it to something larger than 30 seconds because the datafeed listen will keep the connection open for 30 seconds and then return an http status 204 when there are no messages. If the client cuts the connection after 10 seconds that will likely cause an exception.

The biggest problem with an exception being thrown every 10 seconds is that any messages that arrive between the time of the exception and the creation of the new datafeed will be dropped.

**Comment by malaysf** [comment]
As @jforsell mentioned, the timeout should be larger than 30 seconds, Symphony recommends 35 seconds: https://rest-api.symphony.com/docs/read-messagesevents-stream-v4
