### ISSUE TITLE
unable to send attachments

### ISSUE THREAD

**Issue by balajichekka** [symphonyoss/RestApiClient#38]
V4MessageCreateAsync is giving error when attachment is provided.
The parameter "attachment" must be a file.

**Comment by malaysf** [comment]
Sorry for the belated reply, I believe this may be due to a recent change to the agent. I'll ask the Symphony folks about this one. The Symphony API now requires a content-type header for the attachment section, but my read of the YAML spec does not _require_ this to be specified.
