### ISSUE TITLE
Empty Value in keyManagerToken Header When Posting an OBO Message

### ISSUE THREAD

**Issue by mvu02** [symphonyoss/RestApiClient#46]
Using the NSwag generated code, we are adding a "keyManagerToken" header with an empty value to the HTTP request when sending a message as an OBO message, which occurs because we are setting KeyManagerToken to be null. The correct behavior should be that when keyManagerToken is null, we should not be adding a "keyManagerToken" header to the HTTP request at all.

An example of such a request that is causing a 401 Exception(Invalid session token) is shown here:

POST https://factset-test.symphony.com/agent/v4/stream/D2O6k4x2Z9auvSOQWe8hI3___qFed_VldA/message/create HTTP/1.1
Connection: Keep-Alive
Content-Type: multipart/form-data; boundary=815a3b3a-befb-44bb-b58f-87d24e6eaa5c
Accept: application/json
sessionToken: insert_token_here
keyManagerToken: 
Content-Length: 9783
Host: factset-test.symphony.com #

**Comment by malaysf** [comment]
Closing out as this is now complete.
