### ISSUE TITLE
Real time events in AbstractDatafeedApi

### ISSUE THREAD

**Issue by klettier** [symphonyoss/RestApiClient#48]
Hello,

Is there any plan to implement all [Real time events](https://rest-api.symphony.com/docs/real-time-events-v4) in the [AbstractDatafeedApi](https://github.com/symphonyoss/RestApiClient/blob/master/src/SymphonyOSS.RestApiClient/Api/AgentApi/AbstractDatafeedApi.cs#L201) ?

Thanks,

kévin

**Comment by malaysf** [comment]
@klettier I don't have any immediate plans, but we welcome contributions. If there's something you're looking for, please add it and create a PR.

**Comment by klettier** [comment]
@malaysf Nice I will definitely help you on this

**Comment by klettier** [comment]
Hello,

Could you please allow me to access **ODP** platform ?

```
Requesting Access
New committer on existing project
If you have just become a committer on an existing Foundation-hosted open source project, you should request that the project lead create a new issue in JIRA on your behalf, as follows:

Project: Open Developer Platform (ODP)

Issue Type: Request access to Foundation Dev Pod

Description:

Link to the project in the Foundation's Github organisation

User info of the new committer(s) on the project (each committer will receive their own User Account):

Name

Surname

Email

Organisation
```

Thanks in advance

**Comment by malaysf** [comment]
@klettier Can you please provide me with the info required to make the request?

Name

Surname

Email

Organisation

**Comment by klettier** [comment]
![image](https://user-images.githubusercontent.com/3425823/35637823-a8f8203e-06b5-11e8-9d58-7f5ac74de02c.png)

**Comment by malaysf** [comment]
@klettier Can you please start by signing up for a 14 day trial to ODP: http://symphony.foundation/odp

and sign the SSF CLA:
https://symphonyoss.atlassian.net/wiki/spaces/FM/pages/62783509/Contribution

@maoo can help if you have any questions

**Comment by klettier** [comment]
Just to let you know that I submitted the form today

**Comment by klettier** [comment]
Hello,

I started the add of new events by refactoring the **AbstractDatafeedApi** and apply the pattern [here](https://docs.microsoft.com/en-us/dotnet/standard/events/how-to-handle-multiple-events-using-event-properties) to avoid **Event** duplication (Property + Field), don't hesitate to take a look and tell me what you think.

I will add more events in the next few days.

kévin

**Comment by tchitnis** [comment]
Hi @klettier,

Is there a PR for this yet?

Thanks,
Tanvi

**Comment by klettier** [comment]
Hi @tchitnis,

No because I didn't get any feedback yet and I'm working with another solution based on #50 that let the client decide on which events he wants to subscribe and that is full async. 
I'm currently in holiday but will provide a PR for #50 as a library (without any static, full DI, and with default consumer strategies)  soon. 

kevin

**Comment by klettier** [comment]
Hello,

My trial is finished and I have signed the Licence agreement, could you give a new access ?

Thanks in advance

**Comment by maoo** [comment]
Hi @klettier, I'll get back to you on this shortly. Thanks.
