### ISSUE TITLE
Include MIT licenced code?

### ISSUE THREAD

**Issue by jforsell** [symphonyoss/RestApiClient#6]
We can work around the fact that swagger-codegen (C#) does not currently support polymorphism using a reworked version of this .NET fiddle: https://dotnetfiddle.net/ELcvnk

The code is licenced under the MIT licence, and will be significantly adapted for this project. What do we need to do to reuse this code - can its MIT licence header file be added to the NOTICE?

**Comment by maoo** [comment]
MIT allows to distribute and sub-license code, as explained on http://programmers.stackexchange.com/a/105926

It is unclear to me if/how we need to specify the original copyright (as mentioned in the link above)

I'd like to get a legal/expert opinion on this, @mindthegab ?

**Comment by mindthegab** [comment]
Yes please check with Aaron. 

In Apache you typically have a line in the NOTICE (or DEPENDENCIES) file mentioning that the code contains other licenses.


-- 
Gabriele Columbro
Executive Director, Symphony Software Foundation

**Comment by maoo** [comment]
Added to https://github.com/symphonyoss/RestApiClient/blob/master/NOTICE.txt , closing this issue.
